/*----------------------------------------------------------
MASV: 20127072 - 20127091 - 20127102 - 20127424
HO TEN CAC THANH VIEN NHOM: Lê Võ Huỳnh Thanh - Lê Trọng Anh Tú - Hoàng Hữu Minh An - Trần Tiến Hoàng
LAB: 03 - NHOM 09
----------------------------------------------------------*/

-- a) Viết script tạo Database có tên QLSVNhom.
USE master
GO

IF DB_ID('QLSVNhom') IS NOT NULL
	DROP DATABASE QLSVNhom
GO

CREATE DATABASE QLSVNhom
GO

USE QLSVNhom
GO
 
-- b) Viết script tạo mới các Table SINHVIEN, NHANVIEN, LOP, HOCPHAN, BANGDIEM như mô tả trên.
CREATE TABLE SINHVIEN
(
	MASV VARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL
 
	CONSTRAINT PK_SV
	PRIMARY KEY(MASV)
)
 
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY VARCHAR(20)
 
	CONSTRAINT PK_NV
	PRIMARY KEY(MANV)
)
 
CREATE TABLE LOP
(
	MALOP VARCHAR(20),
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
 
	CONSTRAINT PK_LOP
	PRIMARY KEY(MALOP)
)
 
CREATE TABLE HOCPHAN
(
	MAHP VARCHAR(20),
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT
 
	CONSTRAINT PK_HP
	PRIMARY KEY(MAHP)
)
 
CREATE TABLE BANGDIEM
(
	MASV VARCHAR(20),
	MAHP VARCHAR(20),
	DIEMTHI VARBINARY(MAX)
 
	CONSTRAINT PK_BD
	PRIMARY KEY(MASV, MAHP)
)

USE QLSVnhom
GO

-- c) Viết các Stored procedure sau

-- 1. Tạo master key
IF NOT EXISTS
(
	SELECT *
	FROM sys.symmetric_keys
	WHERE symmetric_key_id = 101
)
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'BMCSDL'
GO
-- 2. Tạo certificate
IF NOT EXISTS
(
	SELECT *
	FROM sys.certificates
	WHERE name = 'MyCert'
)
CREATE CERTIFICATE MyCert WITH SUBJECT = 'MyCert'
GO

-- (i). Insert vào NHANVIEN, mã hoá mật khẩu bằng SHA1, mã hoá lương bằng RSA
IF OBJECT_ID('SP_INS_PUBLIC_NHANVIEN') IS NOT NULL
	DROP PROCEDURE SP_INS_PUBLIC_NHANVIEN
GO

CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN @MaNV VARCHAR(20), @HoTen NVARCHAR(100), @email VARCHAR(20),
					@LuongCB INT, @TenDN NVARCHAR(100), @Matkhau VARCHAR(MAX)
AS
	-- Mã hoá mật khẩu
	DECLARE @hash_pass VARBINARY(MAX)
	SET @hash_pass = HASHBYTES('SHA1', @Matkhau)
 
	-- 3. Tạo key
	DECLARE @create_key VARCHAR(MAX)
	SET @create_key = 'CREATE ASYMMETRIC KEY ' + @MaNV + ' WITH ALGORITHM = RSA_2048 ENCRYPTION BY PASSWORD = ''' + @Matkhau + ''''
	IF NOT EXISTS
	(
		SELECT *
		FROM sys.asymmetric_keys
		WHERE name = @MaNV
	)
	EXEC(@create_key)
 
	-- 4. Mã hoá sử dụng khoá công khai
	DECLARE @AsymID INT
	SET @AsymID = ASYMKEY_ID(@MaNV)
	DECLARE @luongEnc VARBINARY(MAX)
	SET @luongEnc = ENCRYPTBYASYMKEY(@AsymID, CONVERT(VARCHAR(MAX), @luongCB))
 
	INSERT NHANVIEN VALUES(@MaNV, @HoTen, @email, @luongEnc, @TenDN, @hash_pass, @MaNV)
GO

DELETE FROM NHANVIEN WHERE MANV LIKE 'NV01'
GO

EXEC SP_INS_PUBLIC_NHANVIEN 'NA01', N'NGUYEN VAN A', 'NVA@', 3000000, N'NVA', 'abcd12'
GO
 
-- (ii). Truy vấn dữ liệu nhân viên sau khi giải mã
IF OBJECT_ID('SP_SEL_PUBLIC_NHANVIEN') IS NOT NULL
	DROP PROCEDURE SP_SEL_PUBLIC_NHANVIEN
GO

CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN @TenDN NVARCHAR(100), @Matkhau NVARCHAR(MAX)
AS
	SELECT MANV, HOTEN, EMAIL, CAST(CONVERT(VARCHAR(MAX), DECRYPTBYASYMKEY(ASYMKEY_ID(@TenDN), LUONG, @Matkhau)) AS INT) as LUONGCB
	FROM NHANVIEN
GO

EXEC SP_SEL_PUBLIC_NHANVIEN 'NA01', 'abcd12'
GO

-- d) Viết các stored procedure và chương trình (sử dụng C#) để thực hiện các yêu cầu sau. Đầu file script ghi chú chi tiết như sau:

----- i>

EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', N'NGUYEN VAN A', 'nva@yahoo.com', 3000000, N'NVA', '123456'
GO

EXEC SP_INS_PUBLIC_NHANVIEN 'NV02', N'NGUYEN VAN B', 'nvb@yahoo.com', 2000000, N'NVB', '1234567'
GO

-- Thêm một tài khoản admin
EXEC SP_INS_PUBLIC_NHANVIEN 'admin', N'admin', 'admin@yahoo.com', 1, N'admin', 'admin'

----- ii> Tạo data để kiểm thử
----------- Tạo khóa phụ
ALTER TABLE LOP
ADD
	CONSTRAINT FK_LOP_NHANVIEN
	FOREIGN KEY(MANV)
	REFERENCES NHANVIEN
GO

ALTER TABLE SINHVIEN
ADD
	CONSTRAINT FK_SINHVIEN_LOP
	FOREIGN KEY(MALOP)
	REFERENCES LOP
GO

ALTER TABLE BANGDIEM
ADD
	CONSTRAINT FK_BANGDIEM_SINHVIEN
	FOREIGN KEY(MASV)
	REFERENCES SINHVIEN,

	CONSTRAINT FK_BANGDIEM_HOCPHAN
	FOREIGN KEY(MAHP)
	REFERENCES HOCPHAN
GO


-- Viết các Stored procedure
---- i) Stored dùng để thêm mới dữ liệu (Insert) vào table SINHVIEN, trong đó

IF OBJECT_ID('SP_INS_PUBLIC_ENCRYPT_NHANVIEN') IS NOT NULL
	DROP PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN
GO

CREATE PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN @MaNV VARCHAR(20), @HoTen NVARCHAR(100), @email VARCHAR(20),
					@LuongCB INT, @TenDN NVARCHAR(100), @Matkhau VARCHAR(MAX)
AS
	INSERT INTO [NHANVIEN]
	VALUES(@MaNV, @HoTen, @email, @LuongCB, @TenDN, @Matkhau)

GO

---- ii) Stored dùng để truy vấn dữ liệu nhân viên (NHANVIEN)
IF OBJECT_ID('SP_SEL_PUBLIC_ENCRYPT_NHANVIEN') IS NOT NULL
	DROP PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
GO

CREATE PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN @TenDN NVARCHAR(100), @Matkhau NVARCHAR(MAX)
AS
	SELECT MANV, HOTEN, EMAIL, LUONG
	FROM NHANVIEN
GO







